apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: kixyu-books
spec:
  displayName: Kixyu Books
  author:
    name: "Kixyu"
    website: "https://kixyu9527.com"
  description: "极简风格的博客主题，类似于阅读器界面。"
  logo: "https://oss.kixyu9527.com/blog/20251112/28553923-55C5-46A3-B738-E6769A0BDEEB.png"
  homepage: "https://kixyu9527.com"
  repo: "https://github.com/kkyu9527/kixyu-books.git"
  issues: "https://github.com/kkyu9527/kixyu-books/issues"
  version: 0.12.5
  requires: ">2.23.0"
  license:
    - name: "MIT"
      url: "https://github.com/kkyu9527/kixyu-books/blob/main/LICENSE"
  settingName: "kixyu-books-setting"
  configMapName: "kixyu-books-configMap"
